import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/ui/theme-provider";

export const metadata: Metadata = {
  title: "Yashwanth Portfolio",
  description: "Generated by yashwanth mallam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
